### ISSUE TITLE
TODO.txt -> TODO.md

### ISSUE THREAD

**Issue by Andygol** [arysin/dict_uk#18]
Переробити TODO у markdown. А краще завести для цього окремий issue і відмічати пункти по ходу виконання…

----
## До першого випуску

- [ ] додати коментар для омонімів у dict_corp_vis.txt

## Після першого випуску 

- [ ] присвійні прикметники від імен прапорцем

- [ ] розвести омоніми/омографи тощо

- [ ] додати решту населених пунктів України

- [ ] переглянути групування прапорців дієслів

- [ ] наблизити теги словника правил LT до тегів словника корпусу

- [ ] додати скрипт сортування входових файлів словника (після ручного редагування)

- [ ] наразі деяки (коротші) дублети не мають всіх форм, якщо вони перетинаються з формами довшої леми

 > (стягти - стягнути, відвологти - відвологнути, сп'ястися - зіпнутися…)

- [ ] кличний відмінок для займенників та решти іменників

## поміняти теги

- [ ] impr -> imprt (щоб краще відрізняти від imprs)

- [ ] додати тег :geo

## Покращення структури

- [ ] перенести теги базових форм з коду в афікси (?)

- [ ] переписати скрипти з python на groovy

- [ ] замінити скрипти командного рядку сценарієм gradle

### Тестування/регресії 

- [ ] перевіряти лат. в укр. словах

- [ ] перевіряти наявність всіх відмінків

- [ ] різні рівні регресії

## Інше 

- [ ] Firefox/LibreOffice.org addons

- [ ] Вебсторінка для пошуку слів

- [ ] додати словник синонімів

- [ ] додати словник перенесення слів

**Comment by arysin** [comment]
Дякую, перейменував, але справді треба буде їх всіх перенсти в issues.
